//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class AcademyDay {
        
        /// <summary>
        ///   Looks up a localized string similar to: Work days
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.AcademyDay.EntitiesName;
            }
            return global::Resources.AcademyManagment.AcademyDay.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Work days of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.AcademyDay.EntitiesNameOf;
            }
            return global::Resources.AcademyManagment.AcademyDay.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Work day of
        /// </summary>
        public static string EntitiyNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.AcademyDay.EntitiyNameOf;
            }
            return global::Resources.AcademyManagment.AcademyDay.ResourceManager.GetString("EntitiyNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Work day
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.AcademyDay.EntityName;
            }
            return global::Resources.AcademyManagment.AcademyDay.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Day name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.AcademyDay.Name;
            }
            return global::Resources.AcademyManagment.AcademyDay.ResourceManager.GetString("Name", resourceCulture);
        }
    }
}
namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class AcademyDayKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Work days
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Work days of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Work day of
        /// </summary>
        public const string EntitiyNameOf = "EntitiyNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Work day
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Day name
        /// </summary>
        public const string Name = "Name";
    }
}
