//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Course {
        
        /// <summary>
        ///   Looks up a localized string similar to: From Date
        /// </summary>
        public static string DateFrom([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.DateFrom;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("DateFrom", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: To Date
        /// </summary>
        public static string DateTo([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.DateTo;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("DateTo", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Duration From
        /// </summary>
        public static string DurationFrom([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.DurationFrom;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("DurationFrom", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Duration To
        /// </summary>
        public static string DurationTo([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.DurationTo;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("DurationTo", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Courses
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.EntitiesName;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Courses of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.EntitiesNameOf;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Course of
        /// </summary>
        public static string EntitiyNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.EntitiyNameOf;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("EntitiyNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Course
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.EntityName;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Active
        /// </summary>
        public static string IsActive([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.IsActive;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("IsActive", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: name
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.Name;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("Name", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Price
        /// </summary>
        public static string Price([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.Course.Price;
            }
            return global::Resources.AcademyManagment.Course.ResourceManager.GetString("Price", resourceCulture);
        }
    }
}
namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class CourseKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: From Date
        /// </summary>
        public const string DateFrom = "DateFrom";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: To Date
        /// </summary>
        public const string DateTo = "DateTo";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Duration From
        /// </summary>
        public const string DurationFrom = "DurationFrom";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Duration To
        /// </summary>
        public const string DurationTo = "DurationTo";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Courses
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Courses of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Course of
        /// </summary>
        public const string EntitiyNameOf = "EntitiyNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Course
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Active
        /// </summary>
        public const string IsActive = "IsActive";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: name
        /// </summary>
        public const string Name = "Name";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Price
        /// </summary>
        public const string Price = "Price";
    }
}
