//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class JoinToCourse {
        
        /// <summary>
        ///   Looks up a localized string similar to: Registred courses
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.JoinToCourse.EntitiesName;
            }
            return global::Resources.AcademyManagment.JoinToCourse.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Registred courses of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.JoinToCourse.EntitiesNameOf;
            }
            return global::Resources.AcademyManagment.JoinToCourse.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Registred course of
        /// </summary>
        public static string EntitiyNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.JoinToCourse.EntitiyNameOf;
            }
            return global::Resources.AcademyManagment.JoinToCourse.ResourceManager.GetString("EntitiyNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Registered course
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.JoinToCourse.EntityName;
            }
            return global::Resources.AcademyManagment.JoinToCourse.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Register Date
        /// </summary>
        public static string RegisterDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.JoinToCourse.RegisterDate;
            }
            return global::Resources.AcademyManagment.JoinToCourse.ResourceManager.GetString("RegisterDate", resourceCulture);
        }
    }
}
namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class JoinToCourseKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Registred courses
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Registred courses of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Registred course of
        /// </summary>
        public const string EntitiyNameOf = "EntitiyNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Registered course
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Register Date
        /// </summary>
        public const string RegisterDate = "RegisterDate";
    }
}
