//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PaymentCourse {
        
        /// <summary>
        ///   Looks up a localized string similar to: Course payments
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.EntitiesName;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Payments of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.EntitiesNameOf;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Payment of
        /// </summary>
        public static string EntitiyNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.EntitiyNameOf;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("EntitiyNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Course payment
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.EntityName;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is paid
        /// </summary>
        public static string IsPaid([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.IsPaid;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("IsPaid", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Payment date
        /// </summary>
        public static string PaymentDate([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.PaymentDate;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("PaymentDate", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Payment status
        /// </summary>
        public static string PaymentStatus([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.PaymentStatus;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("PaymentStatus", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Refrence number
        /// </summary>
        public static string RefrenceNumber([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.PaymentCourse.RefrenceNumber;
            }
            return global::Resources.AcademyManagment.PaymentCourse.ResourceManager.GetString("RefrenceNumber", resourceCulture);
        }
    }
}
namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PaymentCourseKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Course payments
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Payments of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Payment of
        /// </summary>
        public const string EntitiyNameOf = "EntitiyNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Course payment
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is paid
        /// </summary>
        public const string IsPaid = "IsPaid";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Payment date
        /// </summary>
        public const string PaymentDate = "PaymentDate";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Payment status
        /// </summary>
        public const string PaymentStatus = "PaymentStatus";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Refrence number
        /// </summary>
        public const string RefrenceNumber = "RefrenceNumber";
    }
}
