//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class RoomsDay {
        
        /// <summary>
        ///   Looks up a localized string similar to: Course date from
        /// </summary>
        public static string CourseDateFrom([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.RoomsDay.CourseDateFrom;
            }
            return global::Resources.AcademyManagment.RoomsDay.ResourceManager.GetString("CourseDateFrom", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Course date to
        /// </summary>
        public static string CourseDateTo([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.RoomsDay.CourseDateTo;
            }
            return global::Resources.AcademyManagment.RoomsDay.ResourceManager.GetString("CourseDateTo", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rooms day name
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.RoomsDay.EntitiesName;
            }
            return global::Resources.AcademyManagment.RoomsDay.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Rooms day name of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.RoomsDay.EntitiesNameOf;
            }
            return global::Resources.AcademyManagment.RoomsDay.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Room day name of
        /// </summary>
        public static string EntitiyNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.RoomsDay.EntitiyNameOf;
            }
            return global::Resources.AcademyManagment.RoomsDay.ResourceManager.GetString("EntitiyNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Room day name
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.AcademyManagment.RoomsDay.EntityName;
            }
            return global::Resources.AcademyManagment.RoomsDay.ResourceManager.GetString("EntityName", resourceCulture);
        }
    }
}
namespace Resources.AcademyManagment.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class RoomsDayKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Course date from
        /// </summary>
        public const string CourseDateFrom = "CourseDateFrom";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Course date to
        /// </summary>
        public const string CourseDateTo = "CourseDateTo";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rooms day name
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Rooms day name of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Room day name of
        /// </summary>
        public const string EntitiyNameOf = "EntitiyNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Room day name
        /// </summary>
        public const string EntityName = "EntityName";
    }
}
