//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Person {
        
        /// <summary>
        ///   Looks up a localized string similar to: Admin Name
        /// </summary>
        public static string AdminName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.AdminName;
            }
            return global::Resources.Person.ResourceManager.GetString("AdminName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Email
        /// </summary>
        public static string Email([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.Email;
            }
            return global::Resources.Person.ResourceManager.GetString("Email", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Emergency Phone
        /// </summary>
        public static string EmergencyPhone([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.EmergencyPhone;
            }
            return global::Resources.Person.ResourceManager.GetString("EmergencyPhone", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: People
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.EntitiesName;
            }
            return global::Resources.Person.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: People of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.EntitiesNameOf;
            }
            return global::Resources.Person.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Person of
        /// </summary>
        public static string EntitiyNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.EntitiyNameOf;
            }
            return global::Resources.Person.ResourceManager.GetString("EntitiyNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Person
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.EntityName;
            }
            return global::Resources.Person.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: First Name
        /// </summary>
        public static string FirstName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.FirstName;
            }
            return global::Resources.Person.ResourceManager.GetString("FirstName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Last Name
        /// </summary>
        public static string LastName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.LastName;
            }
            return global::Resources.Person.ResourceManager.GetString("LastName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Cell Phone
        /// </summary>
        public static string Mobile([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.Mobile;
            }
            return global::Resources.Person.ResourceManager.GetString("Mobile", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Password
        /// </summary>
        public static string Password([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.Password;
            }
            return global::Resources.Person.ResourceManager.GetString("Password", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: CV
        /// </summary>
        public static string ResumeURL([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.ResumeURL;
            }
            return global::Resources.Person.ResourceManager.GetString("ResumeURL", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Student name
        /// </summary>
        public static string StudentName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.StudentName;
            }
            return global::Resources.Person.ResourceManager.GetString("StudentName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Teacher name
        /// </summary>
        public static string TeacherName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Person.TeacherName;
            }
            return global::Resources.Person.ResourceManager.GetString("TeacherName", resourceCulture);
        }
    }
}
namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PersonKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Admin Name
        /// </summary>
        public const string AdminName = "AdminName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email
        /// </summary>
        public const string Email = "Email";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Emergency Phone
        /// </summary>
        public const string EmergencyPhone = "EmergencyPhone";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: People
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: People of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Person of
        /// </summary>
        public const string EntitiyNameOf = "EntitiyNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Person
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: First Name
        /// </summary>
        public const string FirstName = "FirstName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Last Name
        /// </summary>
        public const string LastName = "LastName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Cell Phone
        /// </summary>
        public const string Mobile = "Mobile";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Password
        /// </summary>
        public const string Password = "Password";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: CV
        /// </summary>
        public const string ResumeURL = "ResumeURL";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Student name
        /// </summary>
        public const string StudentName = "StudentName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Teacher name
        /// </summary>
        public const string TeacherName = "TeacherName";
    }
}
