//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.CMS.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Article {
        
        /// <summary>
        ///   Looks up a localized string similar to: Text
        /// </summary>
        public static string ContentBody([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Article.ContentBody;
            }
            return global::Resources.CMS.Article.ResourceManager.GetString("ContentBody", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Articles
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Article.EntitiesName;
            }
            return global::Resources.CMS.Article.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Articles of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Article.EntitiesNameOf;
            }
            return global::Resources.CMS.Article.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Article
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Article.EntityName;
            }
            return global::Resources.CMS.Article.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Article of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Article.EntityNameOf;
            }
            return global::Resources.CMS.Article.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Priority
        /// </summary>
        public static string Priority([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Article.Priority;
            }
            return global::Resources.CMS.Article.ResourceManager.GetString("Priority", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Title
        /// </summary>
        public static string Title([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Article.Title;
            }
            return global::Resources.CMS.Article.ResourceManager.GetString("Title", resourceCulture);
        }
    }
}
namespace Resources.CMS.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ArticleKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Text
        /// </summary>
        public const string ContentBody = "ContentBody";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Articles
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Articles of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Article
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Article of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Priority
        /// </summary>
        public const string Priority = "Priority";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Title
        /// </summary>
        public const string Title = "Title";
    }
}
