//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.CMS.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Contact {
        
        /// <summary>
        ///   Looks up a localized string similar to: Text
        /// </summary>
        public static string ContentBody([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.ContentBody;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("ContentBody", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Email
        /// </summary>
        public static string Email([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.Email;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("Email", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Messages
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.EntitiesName;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Messages of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.EntitiesNameOf;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Message
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.EntityName;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Message of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.EntityNameOf;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Cellphone
        /// </summary>
        public static string Mobile([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.Mobile;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("Mobile", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Firstname/Lastname
        /// </summary>
        public static string Name([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Contact.Name;
            }
            return global::Resources.CMS.Contact.ResourceManager.GetString("Name", resourceCulture);
        }
    }
}
namespace Resources.CMS.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ContactKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Text
        /// </summary>
        public const string ContentBody = "ContentBody";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email
        /// </summary>
        public const string Email = "Email";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Messages
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Messages of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Message
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Message of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Cellphone
        /// </summary>
        public const string Mobile = "Mobile";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Firstname/Lastname
        /// </summary>
        public const string Name = "Name";
    }
}
