//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.CMS.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Slider {
        
        /// <summary>
        ///   Looks up a localized string similar to: Description
        /// </summary>
        public static string Description([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Slider.Description;
            }
            return global::Resources.CMS.Slider.ResourceManager.GetString("Description", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sliders
        /// </summary>
        public static string EntitiesName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Slider.EntitiesName;
            }
            return global::Resources.CMS.Slider.ResourceManager.GetString("EntitiesName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Sliders of
        /// </summary>
        public static string EntitiesNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Slider.EntitiesNameOf;
            }
            return global::Resources.CMS.Slider.ResourceManager.GetString("EntitiesNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Slider
        /// </summary>
        public static string EntityName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Slider.EntityName;
            }
            return global::Resources.CMS.Slider.ResourceManager.GetString("EntityName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Slider of
        /// </summary>
        public static string EntityNameOf([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Slider.EntityNameOf;
            }
            return global::Resources.CMS.Slider.ResourceManager.GetString("EntityNameOf", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Image url
        /// </summary>
        public static string ImgUrl([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Slider.ImgUrl;
            }
            return global::Resources.CMS.Slider.ResourceManager.GetString("ImgUrl", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Slider Title
        /// </summary>
        public static string Title([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.CMS.Slider.Title;
            }
            return global::Resources.CMS.Slider.ResourceManager.GetString("Title", resourceCulture);
        }
    }
}
namespace Resources.CMS.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SliderKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Description
        /// </summary>
        public const string Description = "Description";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sliders
        /// </summary>
        public const string EntitiesName = "EntitiesName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Sliders of
        /// </summary>
        public const string EntitiesNameOf = "EntitiesNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Slider
        /// </summary>
        public const string EntityName = "EntityName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Slider of
        /// </summary>
        public const string EntityNameOf = "EntityNameOf";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Image url
        /// </summary>
        public const string ImgUrl = "ImgUrl";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Slider Title
        /// </summary>
        public const string Title = "Title";
    }
}
